with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: "mocks"
packages:
    github.com/ttkopec/klaus-task/internal/db:
        config:
        interfaces:            
            Service:
                config: